name: Snorkling väderkoll

on:
  schedule:
    - cron: "0 6 * * *"   # Kör varje dag 06:00 UTC (08:00 svensk tid)
  workflow_dispatch:       # Gör att du kan köra manuellt i GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run snorkling script
        run: python snorkling_smhi.py
